### ISSUE TITLE
Generate OCC for entire mesh

### ISSUE THREAD

**Issue by personal-coding** [MarilynKeller/HIT#1]
I want to start by saying this is amazing research. Is there a way to generate the occupancy for the entire mesh, instead of just a slice?

**Comment by MarilynKeller** [comment]
Hi, thanks :)

What do you mean by "for the entire mesh" ?

You can evaluate the occupancy in any 3D point, inside or outside the body mesh, for 3D points on a plane like in the slice example, on a 3D points on a 3D grid to evaluate a volume. 

The meshes of the different tissues are generated using marching cube and sampling the occupancy function for a specific tissue.

Does this clarify?

**Comment by MarilynKeller** [comment]
Ok I see, indeed this might be too many points to evaluate. The key is to only sample and evaluate points inside the body. 

So, create a 3D array with coordinates u,v,w, decide on a resolution to convert these indices to 3D points x,y,z.
For each of these points, test if they are inside the body mesh or not, this gives you a mask B (of shape U,V,W)
And then only evaluate the occupancy of points B==True

You could have 
u in [0, 1000] (index)
x in [-0.5, 0.5] meters

This could still give you 3e6 points to evaluate so one way is to evaluate the occupancy by batches or 3e5 or smaller, depending on you manage to load in memory. 

I'd recommend starting with a low resolution, like points spaced by 5cm to test your implementation, and then lower it to see at which resolution you converge towards a fixed set of tissues percentage.

As for the bones, we only predict the long bones because the other ones were too small or thin to be segmented on MRI. With adequate dataset, the approach could be extended to all bones. It all depends on the training dataset.

**Comment by MarilynKeller** [comment]
First make sure you used the same betas in input in both cases.
Second, to test the filtering, might be more visual to set all the outside point to 0,0,0. Then, if your filtering work, all the outside will be red (probably 0,0,0 is in the red, tissue LT)

**Comment by MarilynKeller** [comment]
So seems like you manage to filter outside point :)

What you observe on the last image in normal, we did not régularise the predictions for points that far from the center. Interesting to see though!

**Comment by MarilynKeller** [comment]
STAR shape and pose parameters are different from SMPL, so you would need to fit STAR to the whole HIT SMPL meshes dataset and retrain HIT.
But if you want HIT output for STAR parameters, I'd suggest you just fit SMPL to your input STAR mesh and then feed the obtained SMPL parameters to HIT.
